name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev libudev-dev
      
      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install libusb
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './clausen-desktop-app/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./clausen-desktop-app
        
      - name: Build Electron app
        run: npm run build
        working-directory: ./clausen-desktop-app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release for macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        working-directory: ./clausen-desktop-app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        working-directory: ./clausen-desktop-app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        working-directory: ./clausen-desktop-app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
